import { z } from "zod";

/**
| Cloud Provider   | Cache Header           | Cached Values           | Uncached Values          | Other Values             |
|------------------|------------------------|-------------------------|--------------------------|--------------------------|
| Vercel           | `x-vercel-cache`       | `HIT`, `STALE`          | `MISS`                   |                         |
| Cloudflare       | `cf-cache-status`      | `HIT`, `REVALIDATED`,`UPDATING`, `STALE` | `DYNAMIC`, `EXPIRED`, `MISS`,  `NONE/UNKNOWN`, `BYPASS` |                        |
| AWS CloudFront   | `x-cache`              | `Hit from cloudfront`, `RefreshHit from cloudfront`, `Hit from cloudfront (Using cache for this request)`   | `Miss from cloudfront`,`Miss from cloudfront (Generated by CloudFront)`,`Error from cloudfront`   |                       |
| Fastly           | `x-cache`              | `HIT`, `STALE`          | `MISS`, `EXPIRED`        |                        |
| Akamai           | `x-cache`              | `TCP_HIT`, `TCP_REFRESH_HIT`, `TCP_REF_FAIL_HIT`, `TCP_CLIENT_REFRESH`, `TCP_IMS_HIT`, `TCP_SWAPFAIL`, `TCP_PARTIAL_HIT`, `TCP_RANGE_HIT` | `TCP_MISS`, `TCP_REFRESH_MISS`, `TCP_MISS_RELOAD`, `TCP_EXPIRED_MISS` |
| Google Cloud CDN | `x-gcache`             | `HIT`                   | `MISS`, `EXPIRED`        |                       |
| Microsoft Azure  | `x-msedge-ref`         | `Cache from cloud`, `Cache from edge` | `Refresh from cloud`, `Refresh from edge` |                       |
| KeyCDN           | `x-cache`              | `HIT`, `STALE`          | `MISS`, `EXPIRED`, `REVALIDATED`, `UPDATING` |                      |
| StackPath        | `x-cache-status`       | `HIT`, `REVALIDATED`    | `MISS`                   |                       |
| BunnyCDN         | `x-cache`              | `HIT`, `STALE`          | `MISS`, `BYPASS`, `EXPIRED` |                      |
 */

const providerNames = [
  "Vercel",
  "Cloudflare",
  "AWS CloudFront",
  "Fastly",
  "Akamai",
  "Google Cloud CDN",
  "Microsoft Azure",
  "KeyCDN",
  "StackPath",
  "BunnyCDN",
] as const;

export const cloudProviderSchema = z.object({
  name: z.enum(providerNames),
  cacheHeader: z.string(),
  cached: z.array(z.string()),
  uncached: z.array(z.string()),
  other: z.array(z.string()),
});
export type CloudProvider = z.infer<typeof cloudProviderSchema>;

const cloudProviders: CloudProvider[] = [
  {
    name: "Vercel",
    cacheHeader: "x-vercel-cache",
    cached: ["HIT", "STALE"],
    uncached: ["MISS"],
    other: [],
  },
  {
    name: "Cloudflare",
    cacheHeader: "cf-cache-status",
    cached: ["HIT", "STALE", "REVALIDATED", "UPDATING"],
    uncached: ["DYNAMIC", "EXPIRED", "MISS", "NONE/UNKNOWN", "BYPASS"],
    other: [],
  },
  {
    name: "AWS CloudFront",
    cacheHeader: "x-cache",
    cached: [
      "Hit from cloudfront",
      "RefreshHit from cloudfront",
      "Hit from cloudfront (Using cache for this request)",
    ],
    uncached: [
      "Miss from cloudfront",
      "Miss from cloudfront (Generated by CloudFront)",
      "Error from cloudfront",
    ],
    other: [],
  },
  {
    name: "Fastly",
    cacheHeader: "x-cache",
    cached: ["HIT", "STALE"],
    uncached: ["MISS", "EXPIRED"],
    other: [],
  },
  {
    name: "Akamai",
    cacheHeader: "x-cache",
    cached: [
      "TCP_HIT",
      "TCP_REFRESH_HIT",
      "TCP_REF_FAIL_HIT",
      "TCP_CLIENT_REFRESH",
      "TCP_IMS_HIT",
      "TCP_SWAPFAIL",
      "TCP_PARTIAL_HIT",
      "TCP_RANGE_HIT",
    ],
    uncached: [
      "TCP_MISS",
      "TCP_REFRESH_MISS",
      "TCP_MISS_RELOAD",
      "TCP_EXPIRED_MISS",
    ],
    other: ["TCP_DENIED", "TCP_COOKIE_DENY", "TCP_AUTH_REQUIRED"],
  },
  {
    name: "Google Cloud CDN",
    cacheHeader: "x-gcache",
    cached: ["HIT"],
    uncached: ["MISS", "EXPIRED"],
    other: [],
  },
  {
    name: "Microsoft Azure",
    cacheHeader: "x-msedge-ref",
    cached: ["Cache from cloud", "Cache from edge"],
    uncached: ["Refresh from cloud", "Refresh from edge"],
    other: [],
  },
  {
    name: "KeyCDN",
    cacheHeader: "x-cache",
    cached: ["HIT", "STALE"],
    uncached: ["MISS", "EXPIRED", "REVALIDATED", "UPDATING"],
    other: [],
  },
  {
    name: "StackPath",
    cacheHeader: "x-cache-status",
    cached: ["HIT", "REVALIDATED"],
    uncached: ["MISS"],
    other: [],
  },
  {
    name: "BunnyCDN",
    cacheHeader: "x-cache",
    cached: ["HIT", "STALE"],
    uncached: ["MISS", "BYPASS", "EXPIRED"],
    other: [],
  },
];

export default cloudProviders;
